environment:
  global:
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C C:\\project\\.ci\\appveyor\\run_with_compiler.cmd"

  matrix:
    # Preinstalled Python versions
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

build: false  # Not a C# project, build stuff at the test step instead.
clone_folder: c:\\project

test_script:
  - ps: cd C:\\project

  - "%WITH_COMPILER% %PYTHON%\\Scripts\\pip.exe install -r C:\\project\\requirements_test.txt"
  - "%WITH_COMPILER% %PYTHON%\\Scripts\\pip.exe install ."

  # Twisted's trial does not build entrypoints on Windows so we have
  # to call it directly.
  - "%PYTHON%\\Scripts\\coverage.exe run %PYTHON%\\Scripts\\trial.py tests"

after_test:
  - "%WITH_COMPILER% %PYTHON%\\python.exe setup.py bdist_wheel"
  - "%PYTHON%\\Scripts\\coverage.exe report"

artifacts:
  - path: dist\*
